To create new container for neutron-opflex-agent
noironetworks/ciscoaci-puppet pull request #43
Opened 2021-04-06 09:08 UTC by ansao-aci

2021-04-15 09:44 UTC, rameescm1 approved these changes

2021-04-25 13:54 UTC, tbachman requested changes
I think we'll need to add a new template for the neutron-opflex-agent configuration file, so that we can update the notify and inspect sockets. We probably should also change the opflex-agent templates to refer to the new location for these sockets.

2021-04-25 13:54 UTC, tbachman commented on ciscoaci-puppet/ciscoaci/manifests/neutron_opflex.pp
> +   file {'/etc/neutron-opflex-agent':
Is there a reason why you used neutron-opflex-agent instead of the neutron directory?

2021-04-25 13:54 UTC, tbachman commented on ciscoaci-puppet/ciscoaci/templates/neutron_opflex_supervisord.conf.erb
> +
We'll need an openvswitch monitor in this file as well - if openvswitch gets restarted, the socket from the bind mount becomes stale, so we have to restart the container to get a valid one (see https://github.com/noironetworks/ciscoaci-puppet/blob/queens/ciscoaci-puppet/ciscoaci/templates/opflex_supervisord.conf.erb#L37-L38).

2021-04-25 13:54 UTC, tbachman commented on ciscoaci-puppet/ciscoaci/templates/opflex-agent-ovs.conf.erb
> +       "socket-name": "/var/run/opflex_notify/opflex-agent-notif.sock",
We should also include the inspect socket (pending review comment on the opflex agent patch), so that users would be able to enter the container as non-root users to run the gbp_inspect command.

2021-04-26 13:39 UTC, ansao-aci commented on ciscoaci-puppet/ciscoaci/manifests/neutron_opflex.pp
> +   file {'/etc/neutron-opflex-agent':
I thought to keep these two files in a saparate directory as they are coming from installer unlike other files in neutron directory.

2021-04-26 13:40 UTC, ansao-aci commented on ciscoaci-puppet/ciscoaci/templates/neutron_opflex_supervisord.conf.erb
> +
Ack.

2021-04-26 13:43 UTC, ansao-aci commented on ciscoaci-puppet/ciscoaci/templates/opflex-agent-ovs.conf.erb
> +       "socket-name": "/var/run/opflex_notify/opflex-agent-notif.sock",
So currently, inside the container, gbp_inspect doesnt work with neutron user. (works with root). 
You are proposing to put it in shared volume and then it works for non-root users?

2021-04-26 14:00 UTC, tbachman commented on ciscoaci-puppet/ciscoaci/manifests/neutron_opflex.pp
> +   file {'/etc/neutron-opflex-agent':
Since this is a neutron service, we should (re-)use the existing directory for neutron. People debugging things on OpenStack will be looking for the configuration files there, so we should be consistent.

2021-04-26 14:02 UTC, tbachman commented on ciscoaci-puppet/ciscoaci/templates/opflex-agent-ovs.conf.erb
> +       "socket-name": "/var/run/opflex_notify/opflex-agent-notif.sock",
Right - and also for consistency. IMHO we made a mistake by not putting these sockets in their own subdirectory when we introduce them.... but now we're stuck with it (don't want to break backwards compatibility), so the best thing to do here is fix it in the installers.

2021-04-26 17:18 UTC, ansao-aci commented on ciscoaci-puppet/ciscoaci/manifests/neutron_opflex.pp
> +   file {'/etc/neutron-opflex-agent':
Ack.

2021-04-27 14:41 UTC, tbachman commented
I'm ready to approve this - are any other changes needed for the tripleo patch? Can we abandon the patches to opflex and python-opflex-agent?

2021-04-27 17:38 UTC, ansao-aci commented
There is change pending on tripleo patch. I am currently testing this patch. After that, we can abandon opflex and neutron-opflex-agent patch.

2021-04-29 16:38 UTC, tbachman approved these changes

2021-04-29 16:39 UTC, merged